version: '1.0'
services:
  proxy:
    build: ./proxy/
    ports:
      - "8000:80"
      - "8080:8080"
    networks:
      internal_nw:
        ipv4_address: 172.18.0.2
  backend:
    build: ./main/
    healthcheck:
      test: curl --fail http://localhost:8081/api/clubs || exit 1
      interval: 20s
      timeout: 30s
      retries: 50
      start_period: 20s
    networks:
      internal_nw:
        ipv4_address: 172.18.0.3
  frontend:
    build: ./main/lab4/
    depends_on:
      backend:
        condition: service_healthy
    networks:
      internal_nw:
        ipv4_address: 172.18.0.4

networks:
  internal_nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
  